### ISSUE TITLE
Not compatible with R version 3.2.1

### ISSUE THREAD

**Issue by wrshoemaker** [aramette/otu2ot#2]
The package is not available using the install.packages() function in R. Should I install the package manually or is it just incompatible

**Comment by aramette** [comment]
See installation instruction in file README.md.

**Comment by wrshoemaker** [comment]
Thanks, it's installed. But in your paper, you state that there's a tutorial. I'm not able to find it in the repo or on the supplementals, also the link for supplementals redirects to the paper abstract. 

Is there a way to view the tutorial?

**Comment by aramette** [comment]
I agree that it is a bit hidden on the Frontiers website:
http://journal.frontiersin.org/article/10.3389/fmicb.2014.00601/abstract
check on the right column on the website, the “Presentation 1.zip” file
http://journal.frontiersin.org/file/downloadfile/4290/octet-stream/Presentation%201.ZIP/324/1/112334
This zipped file contains the 5 tutorials.

**Comment by wrshoemaker** [comment]
I see it. Thanks for all your help! Great package so far.

Best,
Will
